runtime: nodejs18
service: web

handlers:
  - url: /static
    static_dir: dist/static

  - url: /(.*\.(json|ico|js|css|png|jpg|jpeg|gif|svg|woff|woff2|ttf|eot))
    static_files: dist/\1
    upload: dist/(.*\.(json|ico|js|css|png|jpg|jpeg|gif|svg|woff|woff2|ttf|eot))

  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html

env_variables:
  NODE_ENV: production
  VITE_API_URL: https://api.pomerene.net