steps:
  # Install Node.js dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # Build the project
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    env:
      - 'NODE_ENV=production'
      - 'REACT_APP_API_URL=https://api.pomerene.net'

  # Deploy the application to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'app'
      - 'deploy'
      - '--version'
      - '$BUILD_ID'
      - '--project'
      - '$PROJECT_ID'
      - '--quiet'

timeout: '1200s'
