steps:
  # Step 1: Install dependencies
  - name: "gcr.io/cloud-builders/yarn"
    args: ["install"]

  # Step 2: Build the React app
  - name: "gcr.io/cloud-builders/yarn"
    args: ["run", "build"]

  # Deploy the application to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--version', '$BUILD_ID', '--quiet']

timeout: '1200s'